### ISSUE TITLE
Скорее всего утечка пямяти

### ISSUE THREAD

**Issue by Heslem** [Rusih100/simple_neural_network#3]
Я использую твою нейронную сеть в своём проекте, и у меня произошла утечка памяти. Visual Studio указывает на float**, они постоянно создаются, возможно где-то это моя ошибка, но это как задачка для тебя, я буду рад если ты попробуешь исправить это.

EDIT 1: Замечаю что если я не запускаю нейронную сеть утечки нет.
EDIT 2: 
for (auto & layer : network_layers) {
    temp = layer.run(temp);
}
Утечка происходит здесь.

EDIT 3:

Я отыскал ошибку. Оператор присваивания у матрицы не удалял прошлые данные, из-за этого происходила утечка

**Comment by rusih100** [comment]
Спасибо за найденную проблему. В течение ближайшего времени исправлю ошибку.

UPD: Утечка исправлена
